services:
  wildfires:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 4000:4000 # http
  postgres:
    image: 'postgis/postgis:17-3.5'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
